logo_title: Jason han

style: black

favicon:

menu:
  '@Me': /me

# 做了域名限制，请改成自己的 KEY
# 若关闭valine 设置enable为false
valine:
  enable: true
  appId: WfUfF6fOXFMYXSDJIUzBR2dV-gzGzoHsz
  appKey: dXLhdTQPQYbUGkswsVg5Es2V

highlight:
  enable: false